name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        
      - name: Set up Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Build and run  Docker Compose
        run: |
          sudo echo "sk-D2dKdz60REhOBU7n68Ca53F290124e138177C8Dd7b151239" >.env

      - name: Build and run  Docker Compose
        run: |
          docker-compose -f docker-compose.yml build
